2021-03-30 12:27:30,305 - app - INFO - Host: 71df7bb904c0.ngrok.io
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Length: 570804
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryS27HBGDNfGHZQcyR
Origin: https://71df7bb904c0.ngrok.io
Referer: https://71df7bb904c0.ngrok.io/
Sec-Ch-Ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
Sec-Ch-Ua-Mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 2001:fd8:b210:9466:9852:a335:7027:6eb5
X-Forwarded-Proto: https


2021-03-30 12:27:30,361 - app - INFO - File: exists
2021-03-30 12:27:30,361 - app - INFO - File: name = happybday_c.jpg
2021-03-30 12:27:30,362 - app - INFO - File: exists | Format: matching
2021-03-30 12:27:34,095 - app - ERROR - ERROR: prediction exceptionExpected Ptr<cv::UMat> for argument 'src'
2021-03-30 12:27:34,176 - app - ERROR - Traceback (most recent call last):
  File "app.py", line 101, in predict
    all_predictions = model.predict(cv_img)
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\ml_model.py", line 78, in predict
    color_coverted = cv2.cvtColor(opencv_image, cv2.COLOR_RGB2BGR)
TypeError: Expected Ptr<cv::UMat> for argument 'src'

2021-03-30 13:17:20,333 - app - INFO - POST: success
2021-03-30 13:17:20,380 - app - INFO - # of files in request: 1
2021-03-30 13:17:20,381 - app - INFO - Host: 72a8c75a0316.ngrok.io
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Length: 570558
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryOPcbb9wAs6Fzuxb2
Origin: https://72a8c75a0316.ngrok.io
Referer: https://72a8c75a0316.ngrok.io/
Sec-Ch-Ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
Sec-Ch-Ua-Mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 2001:fd8:b210:9466:9852:a335:7027:6eb5
X-Forwarded-Proto: https


2021-03-30 13:17:20,381 - app - INFO - File: exists
2021-03-30 13:17:20,381 - app - INFO - File: name = happybday2.jpg
2021-03-30 13:17:20,381 - app - INFO - File: exists | Format: matching
2021-03-30 13:17:26,744 - app - ERROR - ERROR: prediction exceptionname 'img_pil' is not defined
2021-03-30 13:17:27,300 - app - ERROR - Traceback (most recent call last):
  File "app.py", line 101, in predict
    all_predictions = model.predict(cv_img)
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\ml_model.py", line 61, in predict
    segmented_staves = Slice(cv_img)
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\segmenter\slicer.py", line 78, in Slice
    segmented_staves.append(crop(img))
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\segmenter\commonfunctions.py", line 64, in crop
    print('Pillow: ', img_pil.mode, img_pil.size)
NameError: name 'img_pil' is not defined

2021-03-30 13:27:52,010 - app - INFO - POST: success
2021-03-30 13:27:52,116 - app - INFO - # of files in request: 1
2021-03-30 13:27:52,116 - app - INFO - Host: 416617b2ccd7.ngrok.io
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Length: 570804
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarynx7k4dQb5RjSH3eH
Origin: https://416617b2ccd7.ngrok.io
Referer: https://416617b2ccd7.ngrok.io/
Sec-Ch-Ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
Sec-Ch-Ua-Mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 2001:fd8:b210:9466:9852:a335:7027:6eb5
X-Forwarded-Proto: https


2021-03-30 13:27:52,117 - app - INFO - File: exists
2021-03-30 13:27:52,117 - app - INFO - File: name = happybday_c.jpg
2021-03-30 13:27:52,117 - app - INFO - File: exists | Format: matching
2021-03-30 13:27:58,513 - app - ERROR - ERROR: prediction exceptionExpected Ptr<cv::UMat> for argument 'src'
2021-03-30 13:27:58,575 - app - ERROR - Traceback (most recent call last):
  File "app.py", line 101, in predict
    all_predictions = model.predict(cv_img)
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\ml_model.py", line 80, in predict
    color_coverted = cv2.cvtColor(opencv_image, cv2.COLOR_RGB2BGR)
TypeError: Expected Ptr<cv::UMat> for argument 'src'

2021-03-30 13:39:26,060 - app - INFO - POST: success
2021-03-30 13:39:26,195 - app - INFO - # of files in request: 1
2021-03-30 13:39:26,195 - app - INFO - Host: c78cedbcfcd8.ngrok.io
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Length: 570558
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryV5CIZVZbvM3dvWOu
Origin: https://c78cedbcfcd8.ngrok.io
Referer: https://c78cedbcfcd8.ngrok.io/
Sec-Ch-Ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
Sec-Ch-Ua-Mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 2001:fd8:b210:9466:9852:a335:7027:6eb5
X-Forwarded-Proto: https


2021-03-30 13:39:26,195 - app - INFO - File: exists
2021-03-30 13:39:26,195 - app - INFO - File: name = happybday2.jpg
2021-03-30 13:39:26,195 - app - INFO - File: exists | Format: matching
2021-03-30 13:39:33,146 - app - ERROR - ERROR: prediction exceptionconversion from L to RBG not supported
2021-03-30 13:39:33,440 - app - ERROR - Traceback (most recent call last):
  File "C:\Users\aroue\anaconda3\lib\site-packages\PIL\Image.py", line 1015, in convert
    im = self.im.convert(mode, dither)
ValueError: conversion from 1 to RBG not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 101, in predict
    all_predictions = model.predict(cv_img)
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\ml_model.py", line 61, in predict
    segmented_staves = Slice(cv_img)
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\segmenter\slicer.py", line 78, in Slice
    segmented_staves.append(crop(img))
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\segmenter\commonfunctions.py", line 67, in crop
    return resized_img.convert('RBG')
  File "C:\Users\aroue\anaconda3\lib\site-packages\PIL\Image.py", line 1020, in convert
    im = im.convert(mode, dither)
ValueError: conversion from L to RBG not supported

2021-03-30 13:54:28,734 - app - INFO - POST: success
2021-03-30 13:54:28,795 - app - INFO - # of files in request: 1
2021-03-30 13:54:28,795 - app - INFO - Host: 2e351e964587.ngrok.io
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Length: 570558
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryxuqsAADoXlZjB5KB
Origin: https://2e351e964587.ngrok.io
Referer: https://2e351e964587.ngrok.io/
Sec-Ch-Ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
Sec-Ch-Ua-Mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 2001:fd8:b210:9466:9852:a335:7027:6eb5
X-Forwarded-Proto: https


2021-03-30 13:54:28,810 - app - INFO - File: exists
2021-03-30 13:54:28,810 - app - INFO - File: name = happybday2.jpg
2021-03-30 13:54:28,810 - app - INFO - File: exists | Format: matching
2021-03-30 13:54:34,350 - app - ERROR - ERROR: prediction exceptionExpected Ptr<cv::UMat> for argument 'src'
2021-03-30 13:54:34,426 - app - ERROR - Traceback (most recent call last):
  File "app.py", line 101, in predict
    all_predictions = model.predict(cv_img)
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\ml_model.py", line 82, in predict
    color_coverted = cv2.cvtColor(opencv_image, cv2.COLOR_GRAY2BGR)
TypeError: Expected Ptr<cv::UMat> for argument 'src'

2021-03-30 14:00:51,083 - app - INFO - POST: success
2021-03-30 14:00:51,152 - app - INFO - # of files in request: 1
